/**
 * Shared CLI-reference model + renderers.
 *
 * Each shipped agent CLI exports a `descriptor: CliDescriptor` describing its
 * commands and flags in a STRUCTURED shape (name / usage / description per
 * command). Those descriptors are collected in `src/cli-descriptors.ts`
 * (`allDescriptors`). Two consumers read them:
 *
 *   1. The CLIs themselves render `--help` output via `renderHelp`.
 *   2. `scripts/gen-cli-reference.ts` renders the canonical markdown doc
 *      (`docs/agent-cli-reference.md`) via `renderCliReference`, and a vitest
 *      drift guard fails if the committed doc diverges from the descriptors.
 *
 * Keep the descriptor shape structured (do NOT collapse commands to freeform
 * strings) so it can later feed tool schemas as well as docs.
 *
 * This module holds only the type + pure renderers — it does NOT import any CLI
 * module, so there is no import cycle (the CLIs import `renderHelp` from here).
 */

/** A single subcommand or invocation form of a CLI. */
export interface CliCommand {
  /** Full usage line, e.g. `create --agent <id> --title "Label" "prompt"`. */
  usage: string;
  /** One-line description of what this command does. */
  description: string;
}

/** Structured description of a shipped agent CLI. */
export interface CliDescriptor {
  /** Canonical CLI name, e.g. `mission-cli`. Used for sorting + coverage. */
  name: string;
  /** Runtime entry point relative to project root, e.g. `dist/mission-cli.js`. */
  binary: string;
  /** One-line summary of the CLI's purpose. */
  summary: string;
  /** Whether this CLI ships to the fleet. Only ship=true CLIs are documented. */
  ship: boolean;
  /** Structured list of the CLI's commands / invocation forms. */
  commands: CliCommand[];
  /** Optional extra notes (behavioral caveats, env requirements, etc.). */
  notes?: string[];
}

/** Literal marker lines that fence the generated CLI section. */
export const BEGIN_MARKER = '<!-- BEGIN GENERATED: cli-reference -->';
export const END_MARKER = '<!-- END GENERATED: cli-reference -->';

const GENERATED_BANNER =
  '<!-- DO NOT EDIT — generated by scripts/gen-cli-reference.ts. ' +
  'Run `npm run gen:cli-docs` to regenerate. -->';

/**
 * Plain-text help for a single CLI, printed on `--help` / `-h`.
 */
export function renderHelp(d: CliDescriptor): string {
  const lines: string[] = [];
  lines.push(`${d.name} — ${d.summary}`);
  lines.push('');
  lines.push(`Binary: node ${d.binary}`);
  lines.push('');
  lines.push('Commands:');
  for (const cmd of d.commands) {
    lines.push(`  ${cmd.usage}`);
    lines.push(`      ${cmd.description}`);
  }
  if (d.notes && d.notes.length > 0) {
    lines.push('');
    lines.push('Notes:');
    for (const note of d.notes) {
      lines.push(`  - ${note}`);
    }
  }
  return lines.join('\n');
}

/**
 * Full markdown body for the generated CLI reference doc.
 *
 * Only ship=true descriptors are included, sorted by name for stable output.
 * The CLI section is fenced between the literal BEGIN/END marker lines so the
 * generated block is unambiguous and could be spliced into a larger doc later.
 */
export function renderCliReference(descriptors: CliDescriptor[]): string {
  const shipped = descriptors
    .filter((d) => d.ship)
    .sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [];
  lines.push(BEGIN_MARKER);
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# Agent CLI Reference');
  lines.push('');
  lines.push(
    'Canonical reference for the ClaudeClaw agent-facing CLIs. This block is ' +
      'generated from each CLI\'s exported `descriptor` — do not hand-edit it; ' +
      'run `npm run gen:cli-docs` to regenerate. ' +
      'Resolve the project root with `PROJECT_ROOT=$(git rev-parse --show-toplevel)` ' +
      'and invoke a CLI as `node "$PROJECT_ROOT/<binary>" <command>`.',
  );
  lines.push('');
  lines.push('## Index');
  lines.push('');
  for (const d of shipped) {
    lines.push(`- [\`${d.name}\`](#${d.name}) — ${d.summary}`);
  }
  lines.push('');

  for (const d of shipped) {
    lines.push(`## ${d.name}`);
    lines.push('');
    lines.push(d.summary);
    lines.push('');
    lines.push(`Binary: \`node ${d.binary}\``);
    lines.push('');
    lines.push('### Commands');
    lines.push('');
    for (const cmd of d.commands) {
      lines.push(`- \`${cmd.usage}\` — ${cmd.description}`);
    }
    lines.push('');
    if (d.notes && d.notes.length > 0) {
      lines.push('### Notes');
      lines.push('');
      for (const note of d.notes) {
        lines.push(`- ${note}`);
      }
      lines.push('');
    }
  }

  lines.push(END_MARKER);

  // Single trailing newline.
  return lines.join('\n').replace(/\n+$/, '') + '\n';
}

/**
 * Compact CLI index for injection into an agent's system prompt.
 *
 * Unlike `renderCliReference` (the full markdown doc), this is a terse listing:
 * a short heading, a one-line routing rule, a pointer to the full doc, then one
 * bullet per ship=true CLI (sorted by name). NO marker fences — this text is
 * appended to a persona prompt, not spliced into a generated doc.
 */
export function renderCliIndex(descriptors: CliDescriptor[]): string {
  const shipped = descriptors
    .filter((d) => d.ship)
    .sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [];
  lines.push('## Agent CLIs');
  lines.push('');
  lines.push(
    'One-shot work handed to another agent uses mission-cli; recurring jobs use ' +
      'schedule-cli — never fake a one-shot with a far-future cron.',
  );
  lines.push('');
  lines.push(
    'Run each as `node "$PROJECT_ROOT/<binary>"` (resolve $PROJECT_ROOT with ' +
      '`git rev-parse --show-toplevel`); these are NOT bare-PATH commands. Never read ' +
      'or write the store with raw sqlite3 — always go through hive-cli.',
  );
  lines.push('');
  lines.push('Full usage: docs/agent-cli-reference.md');
  lines.push('');
  for (const d of shipped) {
    lines.push(`- \`${d.name}\` (\`${d.binary}\`) — ${d.summary}`);
  }

  return lines.join('\n');
}

/**
 * Normalize line endings for drift comparison. Git's `core.autocrlf` rewrites
 * the committed doc's EOLs on checkout (CRLF on Windows), while the generator
 * always emits LF. Comparing normalized text keeps the drift guard meaningful
 * (it still catches any content change) without being brittle across platforms.
 */
export function normalizeEol(s: string): string {
  return s.replace(/\r\n/g, '\n');
}
