// Gallery — surfaces every generated image/video from the same local source
// folders as the always-on :8090 "BobaCatTrades + Nano Banana" gallery server,
// but served by THIS dashboard so it's same-origin (no CORS) and keeps working
// even if :8090 is down. Read-only: we only list + stream existing files.
//
// ROOTS + SECTIONS below MIRROR ~/.claude/skills/banana-maker/bobacat_server.py
// (its ROOTS / SOURCES). If you add a source folder there, add it here too.
import fs from 'fs';
import path from 'path';

const HOME = process.env.HOME || '/home/itsju';

// Named source roots (mirror of bobacat_server.py ROOTS).
const ROOTS: Record<string, string> = {
  pack: '/mnt/c/Users/itsju/OneDrive/Desktop/From Claude To Mike/bobacattrades',
  nano: '/mnt/c/Users/itsju/OneDrive/Desktop/ai bot stuff/NanoBanana Generations',
  freqplot: `${HOME}/LapClaw/freqtrade/user_data/plot`,
  video: `${HOME}/01_ACTIVE/free-video-maker/renders`,
  avcartoon: '/mnt/c/Users/itsju/OneDrive/Desktop/From Claude To Mike/bobacattrades/discord-avatars/cartoon',
  avphoto: '/mnt/c/Users/itsju/OneDrive/Desktop/From Claude To Mike/bobacattrades/discord-avatars/photo',
  generated: `${HOME}/.claude/skills/banana-maker/output`,
  scratchgif: '/mnt/c/Users/itsju/OneDrive/Desktop/From Claude To Mike/bobacattrades/scratching-gifs',
  comfyui: `${HOME}/gallery-watched/comfyui`,
  higgsfield: `${HOME}/gallery-watched/higgsfield`,
};

interface SourceDef {
  id: string;
  root: keyof typeof ROOTS | string;
  sub: string;
  title: string;
  desc: string;
  exts: string[];
  sort: 'name' | 'mtime';
}

// Shared image+video extension set. Used for every section so a stray jpg/webp/mp4
// dropped into an otherwise-png folder still shows (was the per-section .png-only trap).
const IMG_VID_EXTS = ['.png', '.jpg', '.jpeg', '.jfif', '.webp', '.gif', '.bmp', '.svg', '.mp4', '.webm', '.mov', '.m4v'];

// Section list (mirror of bobacat_server.py SOURCES). Generation folders first
// (newest-first), brand-pack folders below, raw source frames last. .html plots are
// intentionally dropped here since the dashboard renders <img>/<video> tiles only.
const SOURCES: SourceDef[] = [
  { id: 'higgsfield', root: 'higgsfield', sub: '', title: 'Higgsfield Generations', desc: 'Images and videos generated via the Higgsfield cloud (Sora/Kling/Veo/Flux/Soul…) — newest first.', exts: IMG_VID_EXTS, sort: 'mtime' },
  { id: 'comfyui', root: 'comfyui', sub: '', title: 'ComfyUI Generations', desc: 'Images and videos generated by ComfyUI — newest first.', exts: IMG_VID_EXTS, sort: 'mtime' },
  { id: 'nano',  root: 'nano',       sub: '',                title: 'Nano Banana Generations', desc: 'Everything generated into the NanoBanana Generations folder — newest first.',          exts: IMG_VID_EXTS, sort: 'mtime' },
  { id: 'gen',   root: 'generated',  sub: '',                title: 'Generated — Nano Banana', desc: 'Every image/video from the banana-maker skill (default output dir) — newest first.',  exts: IMG_VID_EXTS, sort: 'mtime' },
  { id: 'video', root: 'video',      sub: '',                title: 'Free Video Maker',        desc: 'Renders auto-saved by free-video-maker — newest first.',                              exts: IMG_VID_EXTS, sort: 'mtime' },
  { id: 'sig',   root: 'pack',       sub: 'signals',         title: 'Buy / Sell Signals',      desc: 'Bullish/bearish mascots, BUY/SELL stamps, Discord emotes.',                           exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'sp',    root: 'pack',       sub: 'scratching-post', title: 'Scratching-Post Scenes',  desc: 'Cat clawing candlesticks across art styles, color-matched to your cats.',             exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'sgif',  root: 'scratchgif', sub: '',                title: 'Scratching-Post GIFs',    desc: 'Animated cats using candlesticks as a scratching post — looping GIFs.',                exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'cr',    root: 'pack',       sub: 'cat-recreations', title: 'Cat Recreations',         desc: 'Every folder cat re-drawn: portrait · trader · emote.',                               exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'gl',    root: 'pack',       sub: 'glitch',          title: 'Glitch / RGB-Split',      desc: 'Chromatic aberration + scanlines + VHS distortion.',                                  exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'svg',   root: 'pack',       sub: 'svg-logos',       title: 'Vector Logos',            desc: 'Scalable .svg + transparent PNG brand logos.',                                        exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'avc',   root: 'avcartoon',  sub: '',                title: 'Discord Avatars — Cartoon', desc: 'Brand mascot avatars for the agent Discord profiles.',                              exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'avp',   root: 'avphoto',    sub: '',                title: 'Discord Avatars — Photo', desc: 'Real-photo avatar crops (cat-centered) for each agent.',                              exts: IMG_VID_EXTS, sort: 'name'  },
  { id: 'freq',  root: 'freqplot',   sub: '',                title: 'Freqtrade Plots',         desc: 'Saved charts from freqtrade plot-dataframe / plot-profit.',                           exts: IMG_VID_EXTS, sort: 'mtime' },
  // Raw source stills used to build the cat-recreation art — kept last so the gallery
  // leads with finished work. (bobacattrades/_raw, sibling of the brand-pack folders.)
  { id: 'raw',   root: 'pack',       sub: '_raw',            title: 'Source Frames',           desc: 'Raw source stills used to build the cat-recreation art.',                              exts: IMG_VID_EXTS, sort: 'mtime' },
];

const VID = new Set(['.mp4', '.webm', '.mov', '.m4v']);
const MIME: Record<string, string> = {
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.jfif': 'image/jpeg',
  '.webp': 'image/webp', '.gif': 'image/gif', '.svg': 'image/svg+xml', '.bmp': 'image/bmp',
  '.mp4': 'video/mp4', '.webm': 'video/webm', '.mov': 'video/quicktime', '.m4v': 'video/quicktime',
};

// Only these (root, sub) pairs are valid file requests — locks the file route
// to declared sections (defense in depth on top of the path-traversal check).
const ALLOWED = new Set(SOURCES.map((s) => `${s.root}|${s.sub}`));

// Higgsfield downloads land here (see src/higgsfield.ts). Created on demand so a
// fresh box doesn't need a manual mkdir before the first generation.
export function higgsfieldDir(): string {
  const dir = ROOTS.higgsfield;
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

export interface GalleryFile { name: string; url: string; type: 'image' | 'video'; }
export interface GallerySection {
  id: string; root: string; sub: string;
  title: string; desc: string; count: number; files: GalleryFile[];
}

function baseDir(s: SourceDef): string {
  const r = ROOTS[s.root];
  return s.sub ? path.join(r, s.sub) : r;
}

function safeMtime(p: string): number {
  try { return fs.statSync(p).mtimeMs; } catch { return 0; }
}

// Recursively collect file paths under `dir`, returned RELATIVE to `dir` (POSIX
// separators) so e.g. `comfyui/verify/foo.png` surfaces under the comfyui section.
// Symlinked dirs/files are skipped (Dirent.isDirectory()/isFile() are false for
// symlinks) — keeps the no-symlink security stance and avoids escaping the root.
function walk(dir: string, rel = ''): string[] {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    if (rel) console.warn(`[gallery] cannot read subdir ${dir}: ${String(e)}`);
    return [];
  }
  const out: string[] = [];
  for (const ent of entries) {
    const relPath = rel ? `${rel}/${ent.name}` : ent.name;
    if (ent.isDirectory()) out.push(...walk(path.join(dir, ent.name), relPath));
    else if (ent.isFile()) out.push(relPath);
  }
  return out;
}

function listSection(s: SourceDef): GalleryFile[] {
  const dir = baseDir(s);
  let names: string[];
  try {
    fs.accessSync(dir);
    names = walk(dir);
  } catch (e) {
    // Section folder unreadable (missing dir, perms, OneDrive offline). Log so it
    // leaves a trace instead of the section silently vanishing from the gallery.
    console.warn(`[gallery] section "${s.id}" unreadable at ${dir}: ${String(e)}`);
    return [];
  }
  const exts = new Set(s.exts.map((e) => e.toLowerCase()));
  let files = names.filter((n) => exts.has(path.extname(n).toLowerCase()));
  if (s.sort === 'mtime') {
    files = files
      .map((n) => ({ n, m: safeMtime(path.join(dir, n)) }))
      .sort((a, b) => b.m - a.m)
      .map((x) => x.n);
  } else {
    files = files.sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  }
  const q = (v: string) => encodeURIComponent(v);
  return files.map((n) => ({
    name: n,
    url: `/api/gallery/file?root=${q(String(s.root))}&sub=${q(s.sub)}&name=${q(n)}`,
    type: VID.has(path.extname(n).toLowerCase()) ? 'video' : 'image',
  }));
}

// Light cache so a 60s page-poll doesn't re-scan every folder each request.
let _cache: { ts: number; sections: GallerySection[] } | null = null;
const TTL_MS = 15_000;

export function getGallery(): GallerySection[] {
  const now = Date.now();
  if (_cache && now - _cache.ts < TTL_MS) return _cache.sections;
  const sections: GallerySection[] = [];
  for (const s of SOURCES) {
    if (!ROOTS[s.root]) { console.warn(`[gallery] section "${s.id}" references undefined root "${String(s.root)}"`); continue; }
    const files = listSection(s);
    if (files.length === 0) continue;
    sections.push({ id: s.id, root: String(s.root), sub: s.sub, title: s.title, desc: s.desc, count: files.length, files });
  }
  _cache = { ts: now, sections };
  return sections;
}

/** Drop the cached scan so the next /api/gallery reflects new files immediately
 *  (called after a generation so the new image shows without the 15s wait). */
export function invalidateGalleryCache(): void {
  _cache = null;
}

export function galleryMime(name: string): string {
  return MIME[path.extname(name).toLowerCase()] || 'application/octet-stream';
}

export function moveGalleryFile(
  srcRoot: string, srcSub: string, name: string,
  dstRoot: string, dstSub: string,
): { ok: boolean; error?: string } {
  const srcFull = resolveGalleryFile(srcRoot, srcSub, name);
  if (!srcFull) return { ok: false, error: 'source not found or invalid' };

  if (!ALLOWED.has(`${dstRoot}|${dstSub}`)) return { ok: false, error: 'invalid destination' };
  const dstBase = ROOTS[dstRoot];
  if (!dstBase) return { ok: false, error: 'invalid destination root' };
  const dstDir = dstSub ? path.join(dstBase, dstSub) : dstBase;
  if (!fs.existsSync(dstDir)) return { ok: false, error: 'destination directory does not exist' };

  // `name` may be a relative subpath (sections recurse); the moved file lands FLAT
  // in the destination section, so resolve against its basename only.
  const dstName = path.basename(name);
  const dstFull = path.resolve(dstDir, dstName);
  if (!dstFull.startsWith(path.resolve(dstDir) + path.sep)) return { ok: false, error: 'path traversal rejected' };
  if (srcFull === dstFull) return { ok: false, error: 'source and destination are the same file' };

  try {
    fs.renameSync(srcFull, dstFull);
    invalidateGalleryCache();
    return { ok: true };
  } catch {
    // rename fails across filesystems (e.g. OneDrive paths); copy+delete fallback
    try {
      fs.copyFileSync(srcFull, dstFull);
      fs.unlinkSync(srcFull);
      invalidateGalleryCache();
      return { ok: true };
    } catch (e2) {
      return { ok: false, error: String(e2) };
    }
  }
}

// Resolve a requested file to an absolute path, guaranteeing it stays inside the
// declared section folder (no path traversal). Returns null if invalid/missing.
// `name` may be a relative subpath (e.g. `verify/foo.png`) since sections recurse.
export function resolveGalleryFile(root: string, sub: string, name: string): string | null {
  if (!ALLOWED.has(`${root}|${sub}`)) return null;
  const base = ROOTS[root];
  if (!base || !name) return null;
  // Allow forward-slash subpaths, but reject backslashes, NUL bytes, any '..'
  // segment, and absolute paths so a request can never escape the section folder.
  if (/[\\\0]/.test(name) || name.includes('..') || path.isAbsolute(name)) return null;
  const dir = path.resolve(sub ? path.join(base, sub) : base);
  const full = path.resolve(dir, name);
  // `full` must stay inside `dir` (belt-and-suspenders after the checks above).
  if (full !== dir && !full.startsWith(dir + path.sep)) return null;
  try {
    // lstat (not stat) so a symlink planted in a section folder can't point out.
    const st = fs.lstatSync(full);
    if (!st.isFile() || st.isSymbolicLink()) return null;
    // realpath containment re-check: defeats a symlinked *parent* directory that
    // lstat on the leaf wouldn't catch. realpath must still resolve inside `dir`.
    const real = fs.realpathSync(full);
    const realDir = fs.realpathSync(dir);
    if (real !== realDir && !real.startsWith(realDir + path.sep)) return null;
  } catch {
    return null;
  }
  return full;
}
